# Use an official Node.js runtime as your base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy your package.json and package-lock.json files
COPY package*.json ./

# Install your development dependencies
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Command to run your tests
CMD ["npm", "test"]
